### ISSUE TITLE
Ejercicio: Asignacion de roles al azar

### ISSUE THREAD

**Issue by AquilesCanta** [AquilesCanta/avaloncete#11]
Corran el siguiente programa de python3

```
import zlib, base64
exec(base64.b64decode('aW1wb3J0IG9zCmltcG9ydCByYW5kb20KCmNsZWFyID0gbGFtYmRhOiBvcy5zeXN0ZW0oJ2NscycgaWYgb3MubmFtZT09J250JyBlbHNlICdjbGVhcicpCgoKY2xhc3MgSnVnYWRvcjoKCiAgZGVmIF9faW5pdF9fKHNlbGYsIG5vbWJyZSk6CiAgICBzZWxmLm5vbWJyZSA9IG5vbWJyZQogICAgc2VsZi5yb2wgPSBOb25lCgogIGRlZiBhc2lnbmFyX3JvbCgpOgogICAgcGFzcwoKY2xlYXIoKQpudW1lcm9fanVnYWRvcmVzID0gaW50KGlucHV0KCJJbmdyZXNlIGVsIG51bWVybyBkZSBqdWdhZG9yZXMgKE3DrW5pbW8gNSwgbcOheGltbyAxMCk6ICIpKQppZiBub3QgKDUgPD0gbnVtZXJvX2p1Z2Fkb3JlcyA8PSAxMCk6CiAgcHJpbnQoIlNhbGFtZS4iKQogIGV4aXQoKQpsaXN0YV9qdWdhZG9yZXMgPSBbXQpjb25qdW50b19ub21icmVzID0gc2V0KCkKbWF4X3RhbWFuaW9fbm9tYnJlID0gMApmb3IgaSBpbiByYW5nZSgxLCBudW1lcm9fanVnYWRvcmVzICsgMSk6CiAgY2xlYXIoKQogIG5vbWJyZSA9IGlucHV0KGYiSW5ncmVzZSBlbCBub21icmUgZGVsIGp1Z2Fkb3Ige2l9OiAiKQogIHdoaWxlIG5vdCBub21icmUgb3Igbm9tYnJlLmxvd2VyKCkgaW4gY29uanVudG9fbm9tYnJlczoKICAgIGNsZWFyKCkKICAgIHByaW50KGYiTm9tYnJlICd7bm9tYnJlfScgZXMgZWwgc3RyaW5nIHZhY2lvIG8geWEgZXhpc3RlIikKICAgIG5vbWJyZSA9IGlucHV0KGYiSW5ncmVzZSBlbCBub21icmUgZGVsIGp1Z2Fkb3Ige2l9OiAiKQogIGNvbmp1bnRvX25vbWJyZXMuYWRkKG5vbWJyZS5sb3dlcigpKQogIG1heF90YW1hbmlvX25vbWJyZSA9IG1heChtYXhfdGFtYW5pb19ub21icmUsIGxlbihub21icmUpKQogIGxpc3RhX2p1Z2Fkb3Jlcy5hcHBlbmQoSnVnYWRvcihub21icmUpKQoKbWFsb3MgPSAwCmlmIG51bWVyb19qdWdhZG9yZXMgPCA3OgogIG1hbG9zID0gMAplbGlmIG51bWVyb19qdWdhZG9yZXMgPCAxMDoKICBtYWxvcyA9IDEKZWxzZToKICBtYWxvcyA9IDIKCnJhbmRvbS5zaHVmZmxlKGxpc3RhX2p1Z2Fkb3JlcykKCmZvciBqdWdhZG9yIGluIGxpc3RhX2p1Z2Fkb3JlczoKICBqdWdhZG9yLnJvbCA9ICJwaW5jaGUgc2Vydmlkb3IgZGUgYXJ0dXJvIgpsaXN0YV9qdWdhZG9yZXNbMF0ucm9sID0gIm1lcmxpbiIKbGlzdGFfanVnYWRvcmVzWzFdLnJvbCA9ICJtb3JnYW5hIgpsaXN0YV9qdWdhZG9yZXNbMl0ucm9sID0gInBlcmNpdmFsIgpsaXN0YV9qdWdhZG9yZXNbM10ucm9sID0gImFzZXNpbmEiCmZvciBpIGluIHJhbmdlKDQsIDQgKyBtYWxvcyk6CiAgbGlzdGFfanVnYWRvcmVzW2ldLnJvbCA9ICJtYWxpdG8iCgpyYW5kb20uc2h1ZmZsZShsaXN0YV9qdWdhZG9yZXMpCgpmb3IganVnYWRvciBpbiBsaXN0YV9qdWdhZG9yZXM6CiAgZXNwYWNpb3MgPSBtYXhfdGFtYW5pb19ub21icmUgKyAyIC0gbGVuKGp1Z2Fkb3Iubm9tYnJlKQogIHByaW50KGYie2p1Z2Fkb3Iubm9tYnJlfSB7Jy0nICogZXNwYWNpb3N9IHJvbDoge2p1Z2Fkb3Iucm9sfSIpCgo='))
```

Y escriban un programa que haga lo mismo. El codigo esta "ofuscado" aproposito para que ustedes hagan la ingenieria inversa. Porfa no lo desofusquen. Cualquier cosa me hacen preguntas.

**Comment by rjnocelli** [comment]
Esto es una prueba

**Comment by rjnocelli** [comment]
[avaloncete_prueba.py.zip](https://github.com/AquilesCanta/avaloncete/files/4714340/avaloncete_prueba.py.zip)

**Comment by rjnocelli** [comment]
Aca esta mi version del programa. Lo converti en .zip por que no me lo dejaba subir en otro formato. Tampoco estaba seguro si teniamos que subirlo via git.

[rjnocelli_avaloncete1.py.zip](https://github.com/AquilesCanta/avaloncete/files/4714350/rjnocelli_avaloncete1.py.zip)

**Comment by AquilesCanta** [comment]
Esta perfecto Rama. Estoy impresionado! Se nota que estas laburando un monton. Tengo algunos comentarios nomas.

- El metodo elegir jugadores lo metiste en la clase Jugador, pero por ahi no es la mejor eleccion. Cuando pienses si un método va o no dentro de una clase, simplemente pensa si aquello que representa la clase **hace** lo que hace el metodo. Por ejemplo, la clase Pato puede tener el método volar() pero nunca puede tener el método `imprimir_tablero()`. No se si me explico. En nuestro caso, los jugadores no eligen jugadores.
- La manera en que resolviste los roles es genial! Mucho mejor que como lo hice yo.
- La manera en que limpias la pantalla creo que no funciona en windows, asi que es posible que a la gorda no le ande esa parte.
- El programa que mande yo no diferencia Pepe y pepe, por ejemplo. Es un detalle medio irrelevante pero hace a la observación.
- El print del final, con los guiones, no funciona tan bien con nombres largos, pero la manera esa de imprimir no la conocia. Bien ahi! Ejemplo:
```
4------------------- rol: asesina
Mi nombre es muy largo porque a mi me gusta poner nombres sumamente largos siempre me gusto rol: merlin
1------------------- rol: pinche servidor de arturo
3------------------- rol: morgana
2------------------- rol: percival
 ```

Despues vamos a hacer un ejercicio de diseño para aprender a construir clases. Grande Ramiro! Estoy sumamente impresionado.

**Comment by rjnocelli** [comment]
Gracias por los comentarios Santi!

Respecto el método elegir jugadores, no creo que está dentro de la clase jugador ni tampoco fue mi intención. Tal vez tenga que checkear la indentación. 

Respecto al comentario de los nombre, podría utilizarse el método .upper()/lower() en el if statement y eso resolvería el problema

**Comment by lagorda** [comment]
Viejas, acá les dejo el código que hice, colgué en mandarlo la semana pasada y pensaba mostrarles en la clase del finde, que al final no hicimos.
Le di muchas vueltas y al final me decante por dejar un número de identificación a cada jugador, pensando que luego pueda tener alguna utilidad, aunque no estoy seguro que la tenga.
Por otro lado, en la función inicio() no estaba seguro si usar return o print, y si esa elección era algo importante a considerar en general y en este caso en particular.
También pienso que la función, podría dividirse, por lo menos, en dos. Y puede que haya quedado un poco desprolija, pero es lo mejor que pude hacer.

[avalon.txt](https://github.com/AquilesCanta/avaloncete/files/4748658/avalon.txt)

**Comment by AquilesCanta** [comment]
```
import random

import os

class Jugador:

    def __init__(self, nombre):
        self.__nombre = nombre
        self.__personaje = None
  
    def asignar_personaje(self, identificacion):
        personajes = ("Merlin", "Morgana", "percival", "Asesina", "Servidor de arturo","servido de arturo", "Mordred", "servidor de arturo", "Malardo", "servidor de arturo")
        self.__personaje = personajes[identificacion]
        return self.__personaje

    def __str__(self):
        if  len(self.__nombre) < 10:
            while len(self.__nombre) < 10:
                self.__nombre += "-" 
            return (f"{self.__nombre}-- rol: {self.__personaje}")
        elif len(self.__nombre) > 10:
            cortar_nombre = self.__nombre[:10]
            return (f"{cortar_nombre}-- rol: {self.__personaje}")

def inicio():
    numero_jugadores = int(input("Ingrese el número de jugadores (Mínimo 5, máximo 10): "))
    os.system("cls")
    if numero_jugadores < 5:
        print("sos boludo")
    elif numero_jugadores > 10:
        print("y no tenes huevos")
    else:
        lista_posiciones = []
        for i in range(numero_jugadores):
            lista_posiciones.append(i)
        random.shuffle(lista_posiciones)
        lista_jugadores = []
        for i in range(len(lista_posiciones)):
            nombre = input(f"Ingrese el nombre del jugador {i + 1}: ")
            jugador = Jugador(nombre)
            jugador.asignar_personaje(lista_posiciones[i])
            lista_jugadores.append(jugador)
            os.system("cls")
        for i in range(len(lista_jugadores)):
            print (lista_jugadores[i])

inicio()
```

- *Grave*: __str__ modifica el estado del objeto (modifica el nombre) Eso es un garron. El nombre pasa a tener unos guiones al final. Lo mismo si lo corta. __str__ nunca deberia modificar el estado interno del objeto.
- `print("sos boludo")` Entiendo que da lo mismo lo que imprimas, pero acostumbrate a seguir el ejercicio al pie de la letra. Lo mismo con los roles.
- Fijate que en el programa original, la posicion de los jugadores tambien se mezcla.
- Fijate que pasa si elegis un nombre que excede 10 caracteres.
- En el programa original no esta el rol de mordred.
- Asignar personaje devuelve el rol, pero no se usa para nada. O sea que esa linea se puede borrar.
```
lista_posiciones = []
        for i in range(numero_jugadores):
            lista_posiciones.append(i)
```
- Es lo mismo que lista_posiciones = list(range(numero_jugadores))
```
while len(self.__nombre) < 10:
                self.__nombre += "-" 
```
- Es lo mismo que self.__nombre += (10 - len(self.__nombre)) * "-". Esto igual es un detalle menor. Una cuestion mas idiomatica que otra cosa.
- `os.system("cls")`  Solo funciona en windows.

Igual bien. Cumple su cometido.

Con esto damos por concluido este ejercicio.
