### ISSUE TITLE
Diseñar e implementar un sistema de sesiones

### ISSUE THREAD

**Issue by AquilesCanta** [AquilesCanta/avaloncete#12]
Tienen que elegir como va a funcionar el sistema de sesiones. Se me ocurren dos opciones:
- Un sistema que cuando abris la pagina por primera vez te pregunte el nombre y use eso como una sesion que se guarda en una cookie.
- Un sistema que requiera que te registres y que exija que te logees cada vez que te conectas a la pagina. Probablemente haya mas material dando vueltas para implementar esta opcion. Quiero que lo discutan poniendo pros y cons en este issue y que eligamos una. Pueden mandar un pull request y linkear este issue para proponer ideas.

No se cuelguen, traten de arrancar esto cuanto antes.

**Comment by AquilesCanta** [comment]
Una vez hecha la decision hay varias tareas que se pueden paralelizar.
- Implementar las views necesarias.
- Implementar los templates.
- Implementar los estilos (CSS) de la pagina.

Pueden hacer commits chiquitos que avancen alguna de estas tareas un poco. Mientras mas chico el commit, mejor!

**Comment by rjnocelli** [comment]
De las 2 posibles opciones que plantea Santi la 1ra es la mas practica y sencilla de realizar ya que no requiera almacenamiento permanente de datos. Por otro lado si queremos que los usuarios aparte de guardan los datos de la cuenta como (nombre, email, img perfil, etc) tengan un historial de partidas ganadas/perdidas u guarden otro tipo de información vamos a necesitar un sistema de cuentas. Este último es mucho mas complejo que el primero ya que se deben considerar varias cosas:

- modelo/s que guarden la informacion
- django forms para registracion que conecte al modelo
- posiblemente una view de registracion idependiente al inicio, login, etc
- sistema de login/out
- password hash (no se si es 100% necesario)

Si bien creo que el Avalon funciona perfectamente con el sistema de sesiones/cookies yo optaria por ir por la ultima opcion como para practicar armar el sistema de cuentas que es bastante comun en estos dias.

Que dicen?

**Comment by AquilesCanta** [comment]
Yo te diria que si te animás mandes una pull request. De lo que quieras. Es siempre más fácil discutir con el código en frente. El razonamiento me parece bien. Más que nada porque parece haber más material acerca de creación de cuentas que de cookie-sessions. Vos mandale mecha. Lo que tiene de mágico git es que podés experimentar todo lo que quieras sin tener que preocuparte por las consecuencias.

Acordate, mientras más chico el cambio, mejor. Igual para que esto funcione necesitas agilizar el manejo de las herramientos. Si te toma dos horas armar un pull request es una paja. Pero lo tenés que aceitar para que sea un proceso quasi-instantáneo.

**Comment by AquilesCanta** [comment]
Lo marco como resuelto. Después iremos viendo si necesita extensiones.
